# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="181898d4-6da1-438f-a9cb-6e3e205f0146"